#pragma once
#include <stddef.h>
void (*glAttachShader)(unsigned int, unsigned int);
void (*glBeginTransformFeedback)(unsigned int);
void (*glBindFramebuffer)(unsigned int, unsigned int);
void (*glBindProgramPipeline)(unsigned int);
void (*glBindSamplers)(int, int, const unsigned int *);
void (*glBindTextures)(int, int, const unsigned int *);
void (*glBindTransformFeedback)(unsigned int, unsigned int);
void (*glBlitNamedFramebuffer)(unsigned int, unsigned int, int, int, int, int, int, int, int, int, unsigned int, unsigned int);
void (*glClear)(unsigned int);
void (*glClearColor)(float, float, float, float);
void (*glClearTexSubImage)(unsigned int, int, int, int, int, int, int, int, unsigned int, unsigned int, const void *);
void (*glCompressedTextureSubImage3D)(unsigned int, int, int, int, int, int, int, int, unsigned int, int, const void *);
void (*glCompileShader)(unsigned int);
void (*glCreateBuffers)(int, unsigned int *);
void (*glCreateFramebuffers)(int, unsigned int *);
unsigned int (*glCreateProgram)();
void (*glCreateProgramPipelines)(int, unsigned int *);
void (*glCreateSamplers)(int, unsigned int *);
unsigned int (*glCreateShader)(unsigned int);
void (*glCreateTextures)(unsigned int, int, unsigned int *);
void (*glCreateTransformFeedbacks)(int, unsigned int *);
void (*glDebugMessageCallback)(void *, void *);
void (*glDeleteBuffers)(int, const unsigned int *);
void (*glDeleteFramebuffers)(int, const unsigned int *);
void (*glDeleteProgram)(unsigned int);
void (*glDeleteProgramPipelines)(int, const unsigned int *);
void (*glDeleteSamplers)(int, const unsigned int *);
void (*glDeleteShader)(unsigned int);
void (*glDeleteTextures)(int, const unsigned int *);
void (*glDeleteTransformFeedbacks)(int, const unsigned int *);
void (*glDetachShader)(unsigned int, unsigned int);
void (*glDisable)(unsigned int);
void (*glDrawArraysInstanced)(unsigned int, int, int, int);
void (*glEnable)(unsigned int);
void (*glEndTransformFeedback)();
void (*glFinish)();
void (*glGenTextures)(int, unsigned int *);
void (*glGetCompressedTextureSubImage)(unsigned int, int, int, int, int, int, int, int, int, void *);
void (*glGetTextureSubImage)(unsigned int, int, int, int, int, int, int, int, unsigned int, unsigned int, int, void *);
void (*glLinkProgram)(unsigned int);
void * (*glMapNamedBufferRange)(unsigned int, ptrdiff_t, ptrdiff_t, unsigned int);
void (*glNamedBufferStorage)(unsigned int, ptrdiff_t, const void *, unsigned int);
void (*glNamedFramebufferDrawBuffer)(unsigned int, int);
void (*glNamedFramebufferDrawBuffers)(unsigned int, int, const int *);
void (*glNamedFramebufferReadBuffer)(unsigned int, int);
void (*glNamedFramebufferTextureLayer)(unsigned int, int, unsigned int, int, int);
void (*glProgramParameteri)(unsigned int, unsigned int, int);
void (*glProgramUniform1fv)(unsigned int, int, int, const float *);
void (*glProgramUniform1iv)(unsigned int, int, int, const int *);
void (*glProgramUniform1uiv)(unsigned int, int, int, const unsigned int *);
void (*glProgramUniform2fv)(unsigned int, int, int, const float *);
void (*glProgramUniform3fv)(unsigned int, int, int, const float *);
void (*glProgramUniform4fv)(unsigned int, int, int, const float *);
void (*glSamplerParameteri)(unsigned int, unsigned int, int);
void (*glScissor)(int, int, int, int);
void (*glShaderSource)(unsigned int, int, const char **, const int *);
void (*glTextureBufferRange)(unsigned int, unsigned int, unsigned int, ptrdiff_t, ptrdiff_t);
void (*glTextureStorage3D)(unsigned int, int, unsigned int, int, int, int);
void (*glTextureStorage3DMultisample)(unsigned int, int, unsigned int, int, int, int, int);
void (*glTextureSubImage3D)(unsigned int, int, int, int, int, int, int, int, unsigned int, unsigned int, const void *);
void (*glTextureView)(unsigned int, unsigned int, unsigned int, unsigned int, int, int, int, int);
void (*glTransformFeedbackBufferRange)(unsigned int, int, unsigned int, ptrdiff_t, ptrdiff_t);
void (*glTransformFeedbackVaryings)(unsigned int, int, const char **, unsigned int);
void (*glUseProgramStages)(unsigned int, unsigned int, unsigned int);
void (*glViewport)(int, int, int, int);